base_url = "https://cloudssss.github.io"

title = "风港"

compile_sass = true

generate_feeds = true

theme = "tale-zola"

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
mode = "toggle"
favicon = "/icon/favicon.jpg"
copyright = "Wind Haven"
katex = true
timeformat = "%B %e, %Y"
author = "Wind Haven"
home_url = "/posts"

# Menu items
[[extra.menu]]
name = "Posts"
url = "posts"

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "/"

[extra.footer]
start_year = "2024"  # start year of the site
end_year = "2024"    # end year of the site
info = "Made with Zola with Tala-Zola theme."


[extra.expressions]
home = "Posts"
